### PR TITLE
Fix docs about permissions

### PR DESCRIPTION
**Pull request by JadynWong**
Permissions must be prefixed with EasyAbp.Abp.SettingUi.

https://github.com/EasyAbp/Abp.SettingUi/blob/0a0ca5f23fb5516c4cfce92cb7a84fbf22040c3d/src/EasyAbp.Abp.SettingUi.Application/SettingUiAppService.cs#L62-L81

### CODE REVIEW

**Comment by JadynWong** [comment]
Hi @wakuflair,
Can you review this pr?

**Comment by wakuflair** [comment]
Sure, I will review it this weekend.

**Comment by wakuflair** [comment]
@gdlcf88 
The pefix of permissions has been changed by this [commit](https://github.com/EasyAbp/Abp.SettingUi/commit/b832d59e98f470d8929a66a567d0591c27dc96e8#diff-e0b4180eff957bc2696417f66ac901eba2177834856082b360161661522bfd3bR7),
Is it nesseary to change it? I prefer keeping the prefix short.

**Comment by gdlcf88** [comment]
Hi, @wakuflair.

The prefix `AbpSettingUi` is converted from `EasyAbp.Abp.SettingUi` without the org name prefix `EasyAbp.`.

The org name "EasyAbp" is recorded in `org` of the [module library](https://github.com/EasyAbp/ModuleLibrary/blob/eb185217480deb2fa11e9ddfca2746a0a0be2dbc/index.json#L657)

Thus, if we keep the above rule, the AbpHelper module installer can generate correct module class names, for example:
  * `EasyAbp.Abp.Trees` -> `AbpTreesXxxxModule`
  * `EasyAbp.NotificationService` -> `NotificationServiceXxxxModule`
  * `Volo.Blogging` -> `BloggingXxxxModule`

**Comment by wakuflair** [comment]
@gdlcf88

The prefix of permissions is just used to distinguish between other permissions. 
I kept it short to improve performance a bit.
It's not prefix of classes/modules, so it's nothing to do with ABPHelper.

I want to revert it back, what's your opinion?

**Comment by gdlcf88** [comment]
Using the common prefix may good for classification in permission management UI and keep the same format as other EasyAbp modules. But sure, customizing the names is fine.

**Comment by wakuflair** [comment]
@gdlcf88 I reverted the prefix back to `SettingUi`.

@JadynWong Since https://github.com/EasyAbp/Abp.SettingUi/commit/677681003e49b712908f2cc4918928c5fbdf31c4 reverted it back, so doc fixes are no longer needed.
However, I noticed that you added [some explanation](https://github.com/EasyAbp/Abp.SettingUi/pull/71/files#diff-0b5ca119d2be595aa307d34512d9679e49186307ef94201e4b3dfa079aa89938R327-R334) of `SettingUiPermissions.GroupName`, I think it's helpful for developers.
So would you create another PR only contains the explanation?

**Comment by JadynWong** [comment]
@wakuflair 
Yes, I will do that.

**Pull request closed without merging**
