### PR TITLE
setting properties file amend

### PR DESCRIPTION
**Pull request by linch90**
Remove the SettingProperty 'Type': 'Text', as the SettingUi can provide the default value: 'text' if the file not provided.
There is a scene, I want to amend the settingproperties of "Abp.Localization.DefaultLanguage" , like "Type" to "select", as the implementation, if the setting properties file provide the "Type" => "text", the "select" would be override to "text", this is not the result I want.

### CODE REVIEW

**Comment by linch90** [comment]
```csharp
public override void Define(ISettingDefinitionContext context)
{
            //Define your own settings here. Example:
            //context.Add(new SettingDefinition(HcMinSettings.MySetting1));

            var defaultLanguageSetting =
                context.GetOrNull("Abp.Localization.DefaultLanguage")
                    .WithProperty(SettingUiConst.Group1, "System")
                    .WithProperty(SettingUiConst.Group2, "Localization")
                    .WithProperty(SettingUiConst.Type, "select")
                    .WithProperty(SettingUiConst.Options, "en|zh-Hans");

            context.Add(defaultLanguageSetting);
}
```
As the "Abp.Localization.DefaultLanguage" is defined in settingProperties file, the "Type" would be always "text" even I change it to "select".

**Comment by wakuflair** [comment]
Hi 

Your scene totally makes sense!
However I prefer another way to solve this issue --- Ignore the json value if the setting has been configured by code.
In this way, your code will work(even can be more simple)

What do you think?

**Comment by linch90** [comment]
Ok, that would be fine. I think it's better than the plan I provided. 
Should I close this request, or just recommit the new plan you provide?

**Comment by wakuflair** [comment]
It's great if you can implement it :smile:

**Comment by wakuflair** [comment]
I think it's ok.

Thanks.

**Pull request merged**
